<?php
/*
	Tablas
	Autor: Edgar Rafael Garcia
	Fecha: Julio 2019
*/
define('TABLA_USUARIOS', 'db_users');
define('TABLA_CLIENTES', 'db_clientes');
define('TABLA_WORKORDERS', 'db_workorders');
define('TABLA_WODETALLES', 'db_wodetalle');
define('TABLA_SERVICES', 'db_services');
define('TABLA_PIEZAS', 'db_piezas');
define('TABLA_CARROS', 'db_car');
define('TABLA_PUSH_NOTIFICATION', 'db_push');
define('TABLA_LOG', 'db_log');
define('TABLA_PARAMETROS', 'db_parametros');
define('TABLA_ITEMS', 'db_items');
?>